name: Build image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      profile:
        description: Profile
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PROFILE: ${{ github.event_name == 'workflow_dispatch' && inputs.profile || github.ref }}
    steps:
    - name: 0-1. Maximize space
      # https://github.com/Ninlives/emerge/blob/master/.github/workflows/os.yml#L15
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        echo "Available space:"
        df -h

    - name: 0-2. Checkout repository
      uses: actions/checkout@v4

    - name: 0-3. Install nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes repl-flake
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: 1-1. Build image
      id: build
      run: |
        nix build .#`basename $PROFILE`
        mkdir release
        cp ./result/main.raw ./release/ddnix_image_`basename $PROFILE`_`date +'%Y%m%d'`.img
        echo "release_name=`basename $PROFILE`_`date +'%Y%m%d'`" >> $GITHUB_OUTPUT

    - name: 2-1. Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.PROFILE }}
        name: ${{ steps.build.outputs.release_name }}
        files: release/ddnix_image_*